version: '3.7'

services:
  discovery-server:
    image: abhiraj858/linkedin-app-discovery-server:v1
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    volumes:
      - ./logs/discovery-server:/app/logs/discovery-server
    networks:
      - app-network

  configserver:
    image: abhiraj858/linkedin-app-config-server:v1
    container_name: configserver
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_started
    volumes:
      - ./logs/config-server:/logs/config-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
