apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: abhiraj858/linkedin-app-post-service:v1
          resources:
            limits:
              memory: "400Mi"
              cpu: "200m"
            requests:
              memory: "200Mi"
              cpu: "100m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: "1234567890"
            - name: DB_SERVER
              value: post-db
          ports:
            - containerPort: 9030
---

apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    app: post-service
  ports:
    - port: 80
      targetPort: 9030
