apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: connection-db
spec:
  serviceName: connection-db
  replicas: 1
  selector:
    matchLabels:
      app: connection-db
  template:
    metadata:
      labels:
        app: connection-db
    spec:
      containers:
        - name: connection-db
          image: neo4j:latest
          resources:
            limits:
              memory: "300Mi"
              cpu: "200m"
            requests:
              memory: "250Mi"
              cpu: "100m"
          ports:
            - name: neo4j-http
              containerPort: 7474
            - name: neo4j-bolt
              containerPort: 7687
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
            - name: neo4j-conf
              mountPath: /conf
            - name: neo4j-logs
              mountPath: /logs
            - name: neo4j-plugins
              mountPath: /plugins
          env:
            - name: NEO4J_AUTH
              value: "neo4j/test@123"
            - name: NEO4J_dbms_default__database
              value: "linkedin"
            - name: NEO4J_dbms_security_auth__enabled
              value: "false"
          livenessProbe:
            exec:
              command:
                - "neo4j"
                - "status"
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: neo4j-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: "standard-rwo"
        volumeMode: Filesystem
    - metadata:
        name: neo4j-conf
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: "standard-rwo"
        volumeMode: Filesystem
    - metadata:
        name: neo4j-logs
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: "standard-rwo"
        volumeMode: Filesystem
    - metadata:
        name: neo4j-plugins
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: "standard-rwo"
        volumeMode: Filesystem

---

apiVersion: v1
kind: Service
metadata:
  name: connection-db
spec:
  clusterIP: None
  selector:
    app: connection-db
  ports:
    - name: neo4j-http
      port: 7474
      targetPort: 7474
    - name: neo4j-bolt
      port: 7687
      targetPort: 7687
  type: ClusterIP