apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: post-service-db
spec:
  selector:
    matchLabels:
      app: post-service-db
  serviceName: post-service-db
  replicas: 1
  template:
    metadata:
      labels:
        app: post-service-db
    spec:
      containers:
        - name: post-service-db
          image: postgres:latest
          resources:
            limits:
              memory: "240Mi"
              cpu: "200m"
            requests:
              memory: "100Mi"
              cpu: "100m"
          env:
            - name: POSTGRES_DB
              value: post_service_db
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: "1234567890"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: post-service-db
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: post-service-db
          persistentVolumeClaim:
            claimName: post-service-db

  volumeClaimTemplates:
    - metadata:
        name: post-service-db
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: "standard-rwo"
        volumeMode: Filesystem

---

apiVersion: v1
kind: Service
metadata:
  name: post-service-db
spec:
  clusterIP: None
  selector:
    app: post-service-db
  ports:
    - name: post-service-db
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

